### ISSUE TITLE
Tests a 16_nodes scale failing

### ISSUE THREAD

**Issue by laraPPr** [EESSI/test-suite#244]
A number of PyTorch tests are failing when we run them on our cluster. 
- Their running out of memory -> should these be skipped?
- Their hitting the walltime

**Comment by casparvl** [comment]
When you say they are running out of memory, you mean GPU memory? or CPU memory?

We currently don't really have any way for tests to query the amount of GPU memory available (like we do for the CPU memory). Maybe we should I don't know...

Regarding the walltime: what kind of GPUs do you have? And what type of interconnect? The test was created on A100s connected through nvlink locally, and through infiniband between nodes. I'm pretty sure our scaling effiency at 16 nodes is still very high for the test case, but that might not be true for all systems. It may mean we need to increase that walltime.

**Comment by casparvl** [comment]
In terms of memory usage: for CPU memory usage, I get:

```
reframe -c eessi/testsuite/tests/apps/PyTorch/PyTorch_torchvision.py -t CI --system=snellius:gpu_A100 -t 1_node --run --setvar measure_memory_usage=True
[       OK ] (3/4) EESSI_PyTorch_torchvision_GPU %scale=1_node %nn_model=resnet50 %parallel_strategy=ddp %module_name=torchvision/0.16.0-foss-2023a-CUDA-12.1.1 %precision=mixed /06a3b31a @snellius:gpu_A100+default
P: total_throughput: 4290.6 img/sec (r:0, l:None, u:None)
P: througput_per_CPU: 1072.7 img/sec (r:0, l:None, u:None)
P: memory: 4939 MiB (r:0, l:None, u:None)
[       OK ] (4/4) EESSI_PyTorch_torchvision_GPU %scale=1_node %nn_model=resnet50 %parallel_strategy=ddp %module_name=torchvision/0.16.0-foss-2023a-CUDA-12.1.1 %precision=default /7d44b85e @snellius:gpu_A100+default
P: total_throughput: 3122.9 img/sec (r:0, l:None, u:None)
P: througput_per_CPU: 780.7 img/sec (r:0, l:None, u:None)
P: memory: 4249 MiB (r:0, l:None, u:None)
```

for a single node (4 ranks). Indeed, that's slightly higher than the memory requested in https://github.com/EESSI/test-suite/blob/ac1f67d911e0df921ef590294a49e8fe9eb80a89/eessi/testsuite/tests/apps/PyTorch/PyTorch_torchvision.py#L25 which is 1024MB per rank. I'm currently testing with

```
reframe -c eessi/testsuite/tests/apps/PyTorch/PyTorch_torchvision.py -t CI --system=snellius:gpu_A100 -t 16_node --run --setvar measure_memory_usage=True
```

to see if the memory consumption per node goes up with the total amount of ranks (probably a little), I'll report that back here. Feel free to make a PR out of it to increase the requested CPU memory. Again, I'm not sure _if_ CPU memory was your initial issue, or if it was GPU memory?

**Comment by casparvl** [comment]
Hm, we currently have a known issue on our system, that I think I'm hitting... I'll have to retry this later once that issue is resolved...

**Comment by laraPPr** [comment]
CPU because I only tested the 16_node tests on CPU only.

**Comment by casparvl** [comment]
Hmm... this passes on our Rome nodes:

```
$ reframe -c test-suite/eessi/testsuite/tests/apps/PyTorch/PyTorch_torchvision.py -t CI --system=snellius:rome -t 16_nodes --run --setvar measure_memory_usage=True
/gpfs/home4/casparl/EESSI/eessi_test_venv/lib64/python3.9/site-packages/setuptools_scm/_integration/setuptools.py:31: RuntimeWarning:
ERROR: setuptools==53.0.0 is used in combination with setuptools_scm>=8.x

Your build configuration is incomplete and previously worked by accident!
setuptools_scm requires setuptools>=61

Suggested workaround if applicable:
 - migrating from the deprecated setup_requires mechanism to pep517/518
   and using a pyproject.toml to declare build dependencies
   which are reliably pre-installed before running the build tools

  warnings.warn(
WARNING: Environment variable 'EESSI_CVMFS_REPO' is not defined. If you do not intend to use the EESSI software stack, this is perfectly fine. To use EESSI, initialize the EESSI environment before running the test suite.
WARNING: Environment variable 'EESSI_CVMFS_REPO' is not defined. If you do not intend to use the EESSI software stack, this is perfectly fine. To use EESSI, initialize the EESSI environment before running the test suite.
WARNING: Environment variable 'EESSI_CVMFS_REPO' is not defined. If you do not intend to use the EESSI software stack, this is perfectly fine. To use EESSI, initialize the EESSI environment before running the test suite.
WARNING: Environment variable 'EESSI_CVMFS_REPO' is not defined. If you do not intend to use the EESSI software stack, this is perfectly fine. To use EESSI, initialize the EESSI environment before running the test suite.
[ReFrame Setup]
  version:           4.7.0-dev.3+20ccf7af
  command:           '/gpfs/home4/casparl/EESSI/eessi_test_venv/bin/reframe -c test-suite/eessi/testsuite/tests/apps/PyTorch/PyTorch_torchvision.py -t CI --system=snellius:rome -t 16_nodes --run --setvar measure_memory_usage=True'
  launched by:       casparl@tcn1.local.snellius.surf.nl
  working directory: '/gpfs/home4/casparl/EESSI'
  settings files:    '<builtin>', '/gpfs/home4/casparl/EESSI/test-suite/config/surf_snellius.py'
  check search path: (R) '/gpfs/home4/casparl/EESSI/test-suite/eessi/testsuite/tests/apps/PyTorch/PyTorch_torchvision.py'
  stage directory:   '/scratch-shared/casparl/reframe_output/staging'
  output directory:  '/gpfs/home4/casparl/EESSI/reframe_runs/output'
  log files:         '/gpfs/home4/casparl/EESSI/reframe_runs/logs/reframe_20250331_170106.log'

[==========] Running 2 check(s)
[==========] Started on Mon Mar 31 17:01:14 2025+0200

[----------] start processing checks
[ RUN      ] EESSI_PyTorch_torchvision_CPU %scale=16_nodes %nn_model=resnet50 %parallel_strategy=ddp %module_name=torchvision/0.13.1-foss-2022a /009a783c @snellius:rome+default
[ RUN      ] EESSI_PyTorch_torchvision_CPU %scale=16_nodes %nn_model=resnet50 %parallel_strategy=None %module_name=torchvision/0.13.1-foss-2022a /ef8d30c9 @snellius:rome+default
[     SKIP ] (1/2) Skipping test: parallel strategy is 'None', but requested process count is larger than one (128).
[       OK ] (2/2) EESSI_PyTorch_torchvision_CPU %scale=16_nodes %nn_model=resnet50 %parallel_strategy=ddp %module_name=torchvision/0.13.1-foss-2022a /009a783c @snellius:rome+default
P: total_throughput: 1260.7 img/sec (r:0, l:None, u:None)
P: througput_per_CPU: 9.8 img/sec (r:0, l:None, u:None)
P: memory: 31145 MiB (r:0, l:None, u:None)
[----------] all spawned checks have finished

[  PASSED  ] Ran 1/2 test case(s) from 2 check(s) (0 failure(s), 1 skipped, 0 aborted)
[==========] Finished on Mon Mar 31 17:10:05 2025+0200
Log file(s) saved in '/gpfs/home4/casparl/EESSI/reframe_runs/logs/reframe_20250331_170106.log'
```
The run took 9 minutes for me, well within the specified `time_limit`. But... this may actually depend on your interconnect.

Can you describe the number of numa domains, number of cores per node, memory per node, and type of interconnect you have on the system where this fails?

**Comment by casparvl** [comment]
Wait, I was thinking that 31145 MiB is well within the limits, but... it's not. We request 1024 MiB per task, but since this launches one task per _NUMA_ domain, there's not that many tasks on a node (8, in our case). That would mean around 8 GiB is requested, which is clearly not enough. And it means the only reason this test succeeds on my system is because it happens to request the amount of memory proportional to the core count...

I'll rerun with `--setvar exact_memory=True`, and fully expect that to run OOM. Let's see...

Solution would probably be to assign 1 GiB per _core_ that is used, rather than per task.

**Comment by casparvl** [comment]
Yep, ran out of memory. I guess if we change

```
    def required_mem_per_node(self):
        return self.num_tasks_per_node * 1024
```

into

```
    def required_mem_per_node(self):
        return self.num_tasks_per_node * self.num_cpus_per_task * 1024
```

it _should_ probably work. Note that this should at least still lead to memory requests that are _reasonable_: essentially 1 GiB per allocated CPU core. 

Feel like testing that @laraPPr and making a PR for it?

**Comment by laraPPr** [comment]
I'll try later this week
